name: portfolio
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.12
  # Web Framework
  - django>=5.0.0
  - asgiref>=3.7.2
  # HTTP & APIs
  - aiohttp>=3.9.1
  - requests>=2.31.0
  - urllib3>=2.1.0
  - chardet>=5.2.0
  - idna>=3.6
  # Authentication & Security
  - pyjwt>=2.8.0
  - cryptography>=41.0.7
  - cffi>=1.16.0
  # Database
  - psycopg2>=2.9.9
  - sqlparse>=0.4.4
  # Environment Management
  - python-dotenv>=1.0.0
  # Package Management
  - pip>=23.3.1
  - pip:
    # Stock API client
    - alpha-vantage>=2.3.1
    # Authentication
    - django-allauth>=0.58.2
    - oauthlib>=3.2.2
    - python3-openid>=3.2.0
    - requests-oauthlib>=1.3.1
    - defusedxml>=0.7.1
    # Other requirements
   # - foil>=0.2.7
    - iso8601>=1.1.0
    - multidict>=6.0.4
    - attrs>=23.1.0
    - async-timeout>=4.0.3
    - yarl>=1.9.3
    - pyyaml>=6.0.1